from __future__ import annotations

from enum import StrEnum


class Phase(StrEnum):
    GAME_START = "GAME_START"
    NIGHT_START = "NIGHT_START"
    NIGHT_GUARD = "NIGHT_GUARD"
    NIGHT_WOLF_CHAT = "NIGHT_WOLF_CHAT"
    NIGHT_WOLF_VOTE = "NIGHT_WOLF_VOTE"
    NIGHT_SEER = "NIGHT_SEER"
    NIGHT_RESOLVE = "NIGHT_RESOLVE"
    CHECK_WIN_NIGHT = "CHECK_WIN_NIGHT"
    DAY_ANNOUNCE = "DAY_ANNOUNCE"
    DAY_LAST_WORDS = "DAY_LAST_WORDS"
    DAY_SPEECH = "DAY_SPEECH"
    DAY_KNIGHT_INTERRUPT = "DAY_KNIGHT_INTERRUPT"
    DAY_VOTE = "DAY_VOTE"
    DAY_VOTE_PK = "DAY_VOTE_PK"
    DAY_EXILE = "DAY_EXILE"
    CHECK_WIN_DAY = "CHECK_WIN_DAY"
    GAME_END = "GAME_END"
